project/routes/web.php
<?php

use App\Http\Controllers\Dataplants;
use App\Http\Controllers\DataplantsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', [DataplantsController::class, 'index'])->name('dashboard');

Route::middleware(['auth:sanctum', 'verified'])->get('/datacloud/{id}', [DataplantsController::class, 'getPlantData'])->name('datacloud');
Route::middleware(['auth:sanctum', 'verified'])->post('/updatedata/{id}', [DataplantsController::class, 'storeData'])->name('updatedata');

project/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

project/app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

project/resources/views/dashboard.blade.php
<x-app-layout>
<!DOCTYPE html>
    <html>
       

        <body>
            @section('content')
            {{-- <div class="banner">
                
                <div class="banner-text">
                    <h1>
                        <strong>NATUREA</strong>
                    </h1>
                    <h2>L'iot au service de la nature<h4>
                </div>
            </div> --}}
            <div class="pres">
                <img class="rose" src="/images/logo_naturea.svg" alt="">
                <h1 class="title">NATUREA</h1>
                <h2 class="baseline">L'iot au service de la nature</h2>
                <div class="gsquare"></div>
                <img class="plantpng" src="/images/image_2.png" alt="">
                <button class="start">Débuter</button>
                <img class="arrow" src="/images/arrow.png" alt="">
            </div>

            <!-- <div id="jpj">
                <div class="container">
                    <div class="jour">
                        <div class="jour-titre">
                            <h3 class="day-number">JOUR N°XXX</h3>
                            <h4 class="date">02/10/2021</h4>
                        </div>
                        <img class="jour-img" src="images/photo1.svg">
                        <div class="jour-info">
                            <p>Température : Entre XX° et XX°</p>
                            
                            <p>Lumière : Active de XX heure à XX heure</p>
     
                            <p>Humidité : Blabla</p>
                        </div>
                    </div>
                </div>
            </div> -->

            <div id="Mes plantes">
                <div class="container2">
                    <h3 class="pictures-title">Mes plantes</h3>
                    <div class="imgs">
                        <div class = "ligne1">
                            @foreach ($plants as $plant)
                                <a href="{{route('datacloud', ['id' => $plant->id])}}"><img src='images/{{ $plant->url }}' style="width:250px; height:250px;"></img></a>
                            @endforeach
                            <img src="images/photo2.svg" width = 250 height = 250></img>
                            <img src="images/photo3.svg" width = 250 height = 250></img>
                        </div>
                        <div class ="ligne2">
                            <img src="images/photo4.svg" width = 250 height = 250></img>
                            <img src="images/photo5.svg" width = 250 height = 250></img>
                            <img src="images/photo6.svg" width = 250 height = 250></img>
                        </div>
                        <div class ="ligne3">
                            <img src="images/photo7.svg" width = 250 height = 250></img>
                            <img src="images/photo8.svg" width = 250 height = 250></img>
                            <img src="images/photo9.svg" width = 250 height = 250></img>
                        </div>
                </div>
            </div>

            <footer>
                ©NATUREA
            </footer>

<style type="text/css">
.pres{
    position: relative;
    display: flex;
    width: 100%;
}
.gsquare{
    width: 50%;
    background-color: #6CBF8E;
}
.plantpng{
    width: 50%;
}
.baseline{
    position: absolute;
    font-family: Rubik Mono One;
    color: #DCF9E8;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    font-size: 24px;
    width: 500px;
    text-align: center;
    background-color: #6CBF8E;
}
.title{
    position: absolute;
    font-family: Rubik Mono One;
    color: #DCF9E8;
    text-shadow: 0px 12px 0px #616B65;
    top: 40%;
    left: 50%;
    transform: translate(-50%, -50%);
    font-size: 64px;
}
.rose{
    position: absolute;
    top: 38%;
    left: 32%;
    transform: translate(-50%, -50%);
}
.start{
    position: absolute;
    width: 200px;
    height: 70px;
    background: #DCF9E8;
    border-radius: 24px;
    top: 70%;
    left: 50%;
    transform: translate(-50%, -50%);
    font-family: Luckiest Guy;
    color: #404040;
    font-size: 24px;
}
.arrow{
    position: absolute;
    top: 88%;
    left: 50%;
    transform: translate(-50%, -50%);
}
html::-webkit-scrollbar {
  width: 15px;
}
html::-webkit-scrollbar-track {
  background: #404040;
}
::-webkit-scrollbar-thumb {
  background: #DCF9E8;
}
html::-webkit-scrollbar-thumb:hover {
  background: #6CBF8E;
}
p{
    font-family: Rubik Mono One;
}
h3, h4{
    font-family: Luckiest Guy;
}
/* .banner{
    position:relative;
    display:flex;
    width:100%;
    height: 88.6vh;
    background: linear-gradient(rgba(0, 0, 0, 0.45),
        rgba(0, 0, 0, 0.45)), url(/images/bg1.png);
    background-attachment: fixed;
    background-size: cover;
}

.banner-text{
    display: block;
    text-align: center;
    margin: auto;
    color: white
}

.banner-text>h1{
    font-size : 5vw;
}

.banner-text>h2{
    font-size: 1.5vw;
} */

.container{
    min-height: 0vh;
    height : 100vh;
    width:100%;
    display:flex;
    align-items:center;
    justify-content: center;
    background-color : #EDFFF4;
}
.jour{
    background-color : #DCF9E8;
    width : 80%;
    height : 60vh;
    border-radius: 30px;
    box-shadow: -20px 20px #95CAAB;
    padding : 20px;
    display:flex;
    flex-direction: row;
}
.jour-img{
    width: 300px;
    margin-left: 60px;
}
.date{
    color: #6CBF8E;
    font-size: 24px;
    text-align: right
}
.day-number{
    font-size: 30px;
    color: #404040;
}
.jour-info{
    margin-top : 70px;
    margin-left: 25px;
    color: #404040;
}
.jour-info p{
    margin-top: 50px;
}
.pictures-title{
    font-family: Rubik Mono One;
    color: #DCF9E8;
    text-align: left !important;
    font-size: 24px;
}
.container2{
    min-height: 0vh;
    width:100%;
    display:flex;
    flex-direction: column;
    align-items:center;
    justify-content: center;
    background-color : #6CBF8E;
}

.container2 h3{
    margin-top : 40px;
}

.imgs{
    display:flex;
    flex-direction: column;
}

.ligne1{
    flex: auto;
    display:flex;
    flex-direction: row;
}

.ligne2{
    flex: auto;
    display:flex;
    flex-direction: row;
}

.ligne3{
    flex: auto;
    display:flex;
    flex-direction: row;
}

.imgs img{
    margin : 20px;
    border-radius : 40px;
    box-shadow: -10px 10px #a9f6c8;
    transition: 0.3s;
}

.imgs img:hover {
    box-shadow: -20px 20px #a9f6c8;
}


footer{
    height : 15vh;
    width:100%;
    margin-top : auto;
    padding : 30px;
    letter-spacing : 2px;
    transition : 0.6s;
    text-align: center;
    box-shadow : 4px 1px 4px 4px lightgrey;
    background : white;
    margin-top : 40px;
}

</style>



        </body>
    </html>
</x-app-layout>

project/resources/views/navigation-menu.blade.php
<nav x-data="{ open: false }" style="background-color: #6CBF8E; z-index: 1000">
        <head>
            <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=Luckiest+Guy&family=Rubik+Mono+One&display=swap" rel="stylesheet">
        </head>
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8" style="background-color: #6CBF8E;">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->

                <!-- <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <img src="/images/logo_naturea.svg" alt="LOGO">
                    </a>
                </div> -->

                <!-- Navigation Links -->
                
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex" style="background-color: #6CBF8E; font-family: 'Luckiest Guy'; font-size: 24px;">
                    <x-jet-nav-link style="color: #DCF9E8; font-size: 24px;" href="{{route('dashboard')}}">
                        Accueil
                    </x-jet-nav-link>
                    <x-jet-nav-link style="color: #DCF9E8; font-size: 24px;" href="{{route('dashboard').'#Mes plantes'}}">
                        Mes plantes
                    </x-jet-nav-link>

                </div>
            </div>

            <div class="hidden sm:flex sm:items-center sm:ml-6" style="background-color: #6CBF8E;">
                <!-- Teams Dropdown -->
                @if (Laravel\Jetstream\Jetstream::hasTeamFeatures())
                    <div class="ml-3 relative">
                        <x-jet-dropdown align="right" width="60">
                            
                            <x-slot name="content">
                                <div class="w-60">
                                    <!-- Team Management -->
                                    <div class="block px-4 py-2 text-xs text-gray-400">
                                        {{ __('Manage Team') }}
                                    </div>

                                    <!-- Team Settings -->
                                    <x-jet-dropdown-link href="{{ route('teams.show', Auth::user()->currentTeam->id) }}">
                                        {{ __('Team Settings') }}
                                    </x-jet-dropdown-link>

                                    @can('create', Laravel\Jetstream\Jetstream::newTeamModel())
                                        <x-jet-dropdown-link href="{{ route('teams.create') }}">
                                            {{ __('Create New Team') }}
                                        </x-jet-dropdown-link>
                                    @endcan

                                    <div class="border-t border-gray-100"></div>

                                    <!-- Team Switcher -->
                                    <div class="block px-4 py-2 text-xs text-gray-400">
                                        {{ __('Switch Teams') }}
                                    </div>

                                    @foreach (Auth::user()->allTeams() as $team)
                                        <x-jet-switchable-team :team="$team" />
                                    @endforeach
                                </div>
                            </x-slot>
                        </x-jet-dropdown>
                    </div>
                @endif

                <!-- Settings Dropdown -->
                <div class="ml-3 relative" style="background-color: #6CBF8E;">
                    <x-jet-dropdown align="right" width="48">
                        <x-slot name="trigger">
                            @if (Laravel\Jetstream\Jetstream::managesProfilePhotos())
                                <button class="flex text-sm border-2 border-transparent rounded-full focus:outline-none focus:border-gray-300 transition">
                                    <img class="h-8 w-8 rounded-full object-cover" src="{{ Auth::user()->profile_photo_url }}" alt="{{ Auth::user()->name }}" />
                                </button>
                            @else
                                <span class="inline-flex rounded-md">
                                    <button type="button" class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:text-gray-700 focus:outline-none transition" style="background-color: #6CBF8E;">
                                        <!-- {{ Auth::user()->name }}

                                        <svg class="ml-2 -mr-0.5 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                                            <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                        </svg> -->
                                        <img src="/images/logo_user.svg" alt="LOGO" width = 40 height = 40>
                                    </button>
                                </span>
                            @endif
                        </x-slot>

                        <x-slot name="content" style="background-color: #6CBF8E;">
                            <!-- Account Management -->
                            <div class="block px-4 py-2 text-xs text-gray-400">
                                {{ __('Manage Account') }}
                            </div>

                            <x-jet-dropdown-link href="{{ route('profile.show') }}">
                                {{ __('Profile') }}
                            </x-jet-dropdown-link>

                            @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                                <x-jet-dropdown-link href="{{ route('api-tokens.index') }}">
                                    {{ __('API Tokens') }}
                                </x-jet-dropdown-link>
                            @endif

                            <div class="border-t border-gray-100"></div>

                            <!-- Authentication -->
                            <form method="POST" action="{{ route('logout') }}">
                                @csrf

                                <x-jet-dropdown-link href="{{ route('logout') }}"
                                         onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                    {{ __('Log Out') }}
                                </x-jet-dropdown-link>
                            </form>
                        </x-slot>
                    </x-jet-dropdown>
                </div>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden" style="background-color: #6CBF8E;">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-jet-responsive-nav-link href="{{ route('dashboard') }}" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-jet-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="flex items-center px-4">
                @if (Laravel\Jetstream\Jetstream::managesProfilePhotos())
                    <div class="flex-shrink-0 mr-3">
                        <img class="h-10 w-10 rounded-full object-cover" src="{{ Auth::user()->profile_photo_url }}" alt="{{ Auth::user()->name }}" />
                    </div>
                @endif

                <div>
                    <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                    <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
                </div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Account Management -->
                <x-jet-responsive-nav-link href="{{ route('profile.show') }}" :active="request()->routeIs('profile.show')">
                    {{ __('Profile') }}
                </x-jet-responsive-nav-link>

                @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                    <x-jet-responsive-nav-link href="{{ route('api-tokens.index') }}" :active="request()->routeIs('api-tokens.index')">
                        {{ __('API Tokens') }}
                    </x-jet-responsive-nav-link>
                @endif

                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-jet-responsive-nav-link href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                    this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-jet-responsive-nav-link>
                </form>

                <!-- Team Management -->
                @if (Laravel\Jetstream\Jetstream::hasTeamFeatures())
                    <div class="border-t border-gray-200"></div>

                    <div class="block px-4 py-2 text-xs text-gray-400">
                        {{ __('Manage Team') }}
                    </div>

                    <!-- Team Settings -->
                    <x-jet-responsive-nav-link href="{{ route('teams.show', Auth::user()->currentTeam->id) }}" :active="request()->routeIs('teams.show')">
                        {{ __('Team Settings') }}
                    </x-jet-responsive-nav-link>

                    @can('create', Laravel\Jetstream\Jetstream::newTeamModel())
                        <x-jet-responsive-nav-link href="{{ route('teams.create') }}" :active="request()->routeIs('teams.create')">
                            {{ __('Create New Team') }}
                        </x-jet-responsive-nav-link>
                    @endcan

                    <div class="border-t border-gray-200"></div>

                    <!-- Team Switcher -->
                    <div class="block px-4 py-2 text-xs text-gray-400">
                        {{ __('Switch Teams') }}
                    </div>

                    @foreach (Auth::user()->allTeams() as $team)
                        <x-jet-switchable-team :team="$team" component="jet-responsive-nav-link" />
                    @endforeach
                @endif
            </div>
        </div>
    </div>
</nav>

project/resources/views/plant.blade.php
<x-app-layout>
    <div>
        <div style="padding: 50px;">
            <h1 style="text-align: center; padding:10px; font-size: 30px;">{{ $plant->name }}</h1>
            <img src="../../images/{{ $plant->url }}" style="width:300px; height:auto; margin: 0 auto; padding:10px;">

            <div>
                <h3 style="text-align: center; padding:10px;" >Conditions idéales</h3>
                <div style="width:350px; margin: 0 auto; padding:10px;">
                    <div style="width: 100%;"> Températures : {{ $plant->temperature }} °C</div>
                    <div style="width: 100%;"> Humidité : {{ $plant->humidity }} %</div>
                    <div style="width: 100%;"> Luminosité : {{ $plant->brightness }}  Lux</div>
                </div>
            </div>

            <div>
                <h3 style="text-align: center; padding:10px;" >Données en temps réels du capteur</h3>
                    <div style="width:350px; margin: 0 auto; padding:10px;">
                        <div style="width: 100%;"> Températures : <div id="tempcapt" style="display: inline-block;"></div> °C</div>
                        <div style="width: 100%;"> Humidité : <div id="humiditycapt" style="display: inline-block;"></div> %</div>
                        <div style="width: 100%;"> Luminosité : <div id="luxcapt" style="display: inline-block;"></div>  Lux</div>
                    </div>
            </div>

            <div>
                

                    <form method="POST" action="{{ route('updatedata', ['id' => $plant->id]) }}">
                    @csrf

                    <h3 style="text-align: center; padding:10px;" >Historique des données</h3>

                    <div class="flex items-center justify-center mt-4">
                        
                        <x-jet-button class="ml-4">
                        {{ __('Mettre à jour les données') }}   
                        </x-jet-button>
                    </div>
                    </form>

                    <div style="width: 600px; margin: 0 auto; padding-top:20px;">
                        @if ($plantsentries != null)
                        <table>
                                <tr>
                                    <th>Temperature</th>
                                    <th>Humidité</th>
                                    <th>Luminosité</th>
                                    <th>Date</th>
                                </tr>
                            @foreach ($plantsentries as $plantsentrie)
                
                                <tr>
                                    <td>{{ $plantsentrie->temperature }}</td>
                                    <td>{{ $plantsentrie->humidity }}</td>
                                    <td>{{ $plantsentrie->brightness }}</td>
                                    <td>{{ substr($plantsentrie->date, 0, -14) }}</td>
                                </tr>
                                
                            @endforeach
                        </table>
                        @endif

                    </div>

                   


            </div>
        </div>


    </div>
    <style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.js" type="text/javascript"></script>

<script>
    // Changer vos paramètres
    const myOrg = "qq7oqf"
    const typeId = "wipy";
    const deviceId = "b0xaexa4Oxf8xac";

    var tempcapt = document.getElementById("tempcapt");
    var humiditycapt = document.getElementById("humiditycapt");
    var luxcapt = document.getElementById("luxcapt");



    function create_UUID() {
        var dt = new Date().getTime();
        var uuid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
            var r = (dt + Math.random() * 16) % 16 | 0;
            dt = Math.floor(dt / 16);
            return (c == 'x' ? r : (r & 0x3 | 0x8)).toString(16);
        });
        return uuid;
    }

    const clientId = 'a:' + myOrg + ':' + create_UUID();

    client = new Paho.MQTT.Client(myOrg + ".messaging.internetofthings.ibmcloud.com", 443, "", clientId);

    // set callback handlers
    client.onConnectionLost = function (responseObject) {
        console.log("Connection Lost: " + responseObject.errorMessage);
    }

    client.onMessageArrived = function (message) {
        // console.log("Message Arrived: " + message.payloadString)
        const tableau = JSON.parse(message.payloadString)
        for(let key in tableau) {
            console.log(key + ":" + tableau[key]);
        }
        tempcapt.innerHTML = tableau['temperature'];
        humiditycapt.innerHTML = tableau['humidite'];
        luxcapt.innerHTML = tableau['luminosite'];
        // out_msg="Message"+message.payloadString+"<br>";
        // out_msg=out_msg+"msg topic"+message.topic;
        // console.log(out_msg);
    }

    
    



    // Topic pour accéder aux données
    const topic = 'iot-2/type/' + typeId + '/id/' + deviceId + '/evt/status/fmt/json';
    console.log(topic);

    // Called when the connection is made
    function onConnect() {
        console.log("Connected!");
        client.subscribe(topic);
    }

    function onConnectF() {
        console.log(" not Connected!");
    }


    // Changer vos paramètres de connexion
    client.connect({
        onSuccess: onConnect,
        onFailure: onConnectF,
        userName: "a-qq7oqf-seuesleuwe",
        password: "lFam-flgc3&o&(SoCM",
        useSSL: true
    });
</script>

</x-app-layout>

project/resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

project/resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>